version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_springboot_security
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_directory_security
      MYSQL_USER: springsecurity
      MYSQL_PASSWORD: springsecurity
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-mysql-network

volumes:
  mysql_data:

networks:
  springboot-mysql-network:
